server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: IH3018Jbp3B1MLkGGO8YBiVNaB5oiMVs
            client-secret: weLnXuEQ3bDp1YdeAtku91d6RFisLONbdExvn2mvCT2XJVhsu6QHPv8wgwkg65fd
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-amepvrpb215sw37t.us.auth0.com

